<a href="https://colab.research.google.com/github/KhalidaBegam/Workshop-2/blob/main/Prac_week4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
!wget https://archive.ics.uci.edu/static/public/368/facebook+metrics.zip
!unzip facebook+metrics.zip

--2024-08-12 04:28:30--  https://archive.ics.uci.edu/static/public/368/facebook+metrics.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘facebook+metrics.zip’

facebook+metrics.zi     [ <=>                ]  15.90K  --.-KB/s    in 0.07s

2024-08-12 04:28:30 (227 KB/s) - ‘facebook+metrics.zip’ saved [16281]

Archive:  facebook+metrics.zip
  inflating: dataset_Facebook.csv
  inflating: Facebook_metrics.txt

In [14]:

# Import necessary libraries
import pandas as pd
import wget
import zipfile
import os
import urllib.request

In [15]:
# Define the URL for the dataset
url = 'https://archive.ics.uci.edu/dataset/368/facebook+metrics/dataset_Facebook.csv'

In [18]:
# Load the dataset into a pandas DataFrame
df = pd.read_csv('dataset_Facebook.csv', delimiter=';')
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [23]:
df_subset = df[['Type', 'Lifetime Post Total Reach']]

# Step 2: Calculate the average lifetime post total reach for each type
average_reach = df_subset.groupby('Type').mean().reset_index()

# Step 3: Write the result to a new CSV file
output_file_path = 'average_lifetime_post_total_reach.csv'
average_reach.to_csv(output_file_path, index=False)

print(f"Average Lifetime Post Total Reach calculated and saved to '{output_file_path}'.")

Average Lifetime Post Total Reach calculated and saved to 'average_lifetime_post_total_reach.csv'.